agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
agit push -u origin mastergit push -u origin masterssssssssssasdas
